- name: Delete the AWS S3 Bucket
  hosts: localhost
  connection: local
  tasks:
    - name: Remove Bucket
      amazon.aws.s3_bucket:
        name: my-unique-spacelift-test-bucket-99909
        state: absent  # <--- This tells AWS to delete it
        force: true    # <--- This ensures it deletes even if there are files inside
        region: us-east-1
